backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /public
public_folder: /public

collections:
  - label: Pages
    name: pages
    extension: json
    files:
    - label: submission-types
      name: submission-types
      file: /data/submissions-details.json
      create: true
      fields:
            - {label: ID, name: id, widget: number}
            - {label: Title, name: title, widget: string}
            - {label: Description, name: desc, widget: markdown}
            - {label: Date, name: date, widget: datetime}
            - {label: Details, name: details, widget: markdown}
            - {label: Link, name: link, widget: string}


      # - label: Layout
      #   name: layout
      #   widget: hidden
      #   default: blog
      # - label: Title
      #   name: title
      #   widget: string
      # - label: Title
      #   name: title
      #   widget: string
      # - label: Publish Date
      #   name: date
      #   widget: datetime
      # - label: Description
      #   name: desc
      #   widget: markdown
      # - label: Body
      #   name: body
      #   widget: markdown

       