
local_bakend: true
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /public
public_folder: /public

collections:
  - name: "submissions" # Used in routes, e.g., /admin/collections/blog
    label: "Submissions" # Used in the UI
    folder: "/public/data/submissions_data" # The path to the folder where the documents are stored
    extension: json
    format: json
    create: true # Allow users to create new documents in this collection
    slug: "{title}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Details", name: "details", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string", required: false}
      
  - name: "workshops" # Used in routes, e.g., /admin/collections/blog
    label: "Workshops" # Used in the UI
    folder: "/src/data/programme_data" # The path to the folder where the documents are stored
    extension: json
    format: json
    create: true # Allow users to create new documents in this collection
    slug: "programmes" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "ID (set to 0)", name: "id", widget: "string", default: 0}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date_widget", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Contacts", name: "contacts", widget: "markdown"}
      - {label: "Event period", name: "event_period", widget: "markdown"}
      - {label: "Mode", name: "mode", widget: "markdown"}

  - name: "timetable" # Used in routes, e.g., /admin/collections/blog
    label: "Timetable" # Used in the UI
    folder: "/src/data/timetable_data" # The path to the folder where the documents are stored
    extension: json
    format: json
    create: true # Allow users to create new documents in this collection
    slug: "day" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: [
      {
        - label: "Day",
          name: "day",
          widget: "number",
          default: "0",
          required: true
      }
    ]
      

      # - label: "Date"
      #   name: "date"
      #   widget: "date"
      #   default: "2023-08-30"
      #   required: true

      # - label: "Data"
      #   name: "data"
      #   widget: "list"
      #   default: "00:00 - 00:00"
      #   required: true
      #   field: 
      #     - label: "Time" 
      #       name: "time"
      #       widget: "string"
      #       default: "00:00 - 00:00"
      #       required: true

      #     - label: "Or" 
      #       name: "or"
      #       widget: "boolean"
      #       default: "false"
      #       required: true

      #     - label: "Item"
      #       name: "item"
      #       widget: "list"
      #       required: true
      #       field: 
      #         - label: "Text"
      #           name: "text"
      #           widget: "string"
      #           default: "Session XX: XXXX"
      #           required: true

      #         - label: "Location"
      #           name: "location"
      #           widget: "string"
      #           default: "ABC123/123"
      #           required: false

      #         - label: "Has Info"
      #           name: "hasInfo"
      #           widget: "boolean"
      #           default: "false"
      #           required: true
            
          
          

# "day": 3,
#   "date": "30th August",
#   "data" : [],

# {
#       "time": "13:45 - 15:15",
#       "or": true,
#       "item": [
#         {
#           "text": "Session A1: User Studies",
#           "location": "CSE/082X",
#           "hasInfo": true,
#           "info": [
#             {
#                 "id" : "FP1114",
#                 "title" : "Brilliance and Resilience: A New Perspective to the Challenges, Practices and Needs of University Students with Visual Impairments in India",
#                 "authors" : "Tigmanshu Bhatnagar, Vikas Upadhyay, PV Madhusudhan Rao, Nicolai Marquardt, Mark Mio-downik, and Catherine Holloway",
#                 "presenters": "Tigmanshu Bhatnagar",
#                 "contact": [
#                     {
#                         "name" : "Bhatnagar, Tigmanshu",
#                         "email" : "t.bhatnagar.18@ucl.ac.uk"
#                     }
#                 ]
#             },
#             {
#                 "id" : "SP1120",
#                 "title" : "Mapping Virtual Reality Controls to Inform Design of Accessible User Experiences",
#                 "authors" : "Christopher Power, Paul Cairns, and Triskal DeHaven",
#                 "presenters": "Christopher Power",
#                 "contact": [
#                     {
#                         "name" : "Power, Christopher",
#                         "email" : "cdspower@upei.ca"
#                     }
#                 ]
#             },
#             {
#                 "id" : "SP1180",
#                 "title" : "WAM-Studio: A Web-based Digital Audio Workstation To Empower Cochlear Implant Users",
#                 "authors" : "Michel Buffa, Antoine Vidal-Mazuy, Lloyd May, and Marco Winckler",
#                 "presenters": "Marco Winckler",
#                 "contact": [
#                     {
#                         "name" : "Buffa, Michel",
#                         "email" : "michel.buffa@univ-cotedazur.fr"
#                     }
#                 ]
#             },
#             {
#                 "id" : "SP1160",
#                 "title" : "Web Accessibility in Higher Education in Norway: To What Extent are University Websites Accessible?",
#                 "authors" : "Yavuz Inal and Anne Britt Torkildsby",
#                 "presenters": "Anne Britt Torkildsby",
#                 "contact": [
#                     {
#                         "name" : "Inal, Yavuz",
#                         "email" : "yavuz.inal@ntnu.no"
#                     }
#                 ]
#             },
#             {
#                 "id" : "SP1114",
#                 "title" : "Wesee: Digital Cultural Heritage Interpretation for Blind and Low Vision People",
#                 "authors" : "Yalan Luo, Weiyue Lin, Yuhan Liu, Xiaomei Nie, Xiang Qian, and Hanyu Guo",
#                 "presenters": "Yalan Luo",
#                 "contact": [
#                     {	
#                         "name" : "Luo, Yalan",
#                         "email" : "luoyl20@mails.tsinghua.edu.cn"
#                     }
#                 ]
#             }
#           ]
#         }
      

      #       {
      #     "id": 1,
      #         "title": "Full Papers",
      #         "createdAt": "2022-09-23T00:12:02.711Z",
      #         "updatedAt": "2022-10-13T03:36:29.975Z",
      #         "publishedAt": "2022-09-23T08:03:24.609Z",
      #         "descriptions": "Full paper submissions to INTERACT may address any area of human-computer interaction. Each paper will be handled by one of the INTERACT SubCommittees listed below. \n\nOn submission you\nwill be asked to nominate the most appropriate SubCommittee, so please consider the list carefully.",
      #         "details": "\n**Key Dates**\n- Full Paper Submission: 1 February 2023, 23:59 (anywhere on earth)\n- Reviews to authors: 15 March 2023\n- Rebuttals due (requested only for borderline papers): 22 March 2023, 23:59 (anywhere on earth)\n- Notification of acceptance: 5 April 2023\n- Camera-Ready: 14 June 2023, 23:59 (anywhere on earth)\n\n\n\n**Submission and Publication Summary**\n- Reviewing process: Peer-reviewed\n- Anonymous submission: Yes. [Read about the INTERACT anonymity policy](http://interact2023.org/anonymity)\n- Length: [Springer format](https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines), 18 pages + 4 pages for references\n- Video: Optional, 30MB max\n- Online Submission: [PCS Submissions System (Opens Now)](https://new.precisionconference.com/submissions)\n- Proceedings: [Springer LNCS Series](https://link.springer.com/conference/interact)\n\nFull papers are considered for the IFIP TC13 Awards. Read about [Awards](http://interact2023.org/awards).\n\nAt least one author for each accepted submission must register for the conference to be\nincluded in the proceedings.\n\n\n**Author Guidelines**\nPapers should be formatted using the [Springer LNCS format](https://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0). Authors should consult the\n[Springer Authors’ guidelines](https://www.interact2021.org/templates/Springer_Guidelines_for_Authors_of_Proceedings_CS.pdf) and use their proceedings templates, either for [LaTeX](https://www.interact2021.org/templates/llncs2e.zip) or for [Word](https://www.interact2021.org/templates/splnproc1703.zip), to\nprepare their papers. Springer proceedings LaTeX templates are also available in [Overleaf](https://www.overleaf.com/latex/templates/springer-lecture-notes-in-computer-science/kzwwpvhwnvfj#.WsdHOy5uZpg).\n\nAccepted full papers must be presented at the conference and will be published in Springer [LNCS\nSeries.](https://link.springer.com/conference/interact)\n\nAuthors should guarantee the anonymity of their submissions. [Read about Anonymity.](http://interact2023.org/anonymity)\nFull papers may optionally be accompanied by a video not exceeding 30 MB in size. Video stills will\nbe published online and may be used for publicity.\n\n\n**Further Information**\nIf you require any further information please contact the Full Paper CoChairs: Antonio Piccinno and Marta Kristín Lárusdóttir \n\nEmail: [fullpapers@interact2023.org](mailto:fullpapers@interact2023.org)\n\n\n**Interact Programme Committee Sub-Committees**\n\n_Accessibility and assistive technologies_\nExample topics: accessibility of mainstream technologies; HCI for an aging population;  accessibility for people\n with cognitive disabilities; accessibility of virtual and augmented reality systems; implementing the EU Web\n Accessibility Directive; digital companions for older people.\n\n_Design for business and safety/critical interactive systems_\nExample topics: automation; critical interactive systems; healthcare; human error; human work interaction\ndesign; safety; training; transportation; usable security.\n\n_Design of interactive entertainment systems_\nExample topics: educational games; edutainment applications; games and gameful design; playful interactions;\nserious games and toys; TVx.\n\n_HCI Education and Curriculum_\nExample topics: Building an HCI curriculum in a continuously changing technology and application landscape;\ninnovative methods for teaching HCI; approaches to life-long learning; ; continuous development for HCI\npractitioners and researchers; the impact of culture and cognitive style of HCI teaching and learning.\n\n_Human-AI Interaction_\nExample topics: Human-centred design of intelligent systems; personalization; interactive recommender\nsystems; human control of intelligent systems; user trust; controls in automation; ethical aspects of intelligent\nsystems; user-centric explainable AI; human-robot interaction.\n\n_Information visualization_\nExample topics: data representations and interaction techniques; evaluation methods for information\nvisualization techniques; methods for elicitation of user constraints; priorities &amp; processes for visualizing data;\n methods for describing user interaction with visualization tools; visual analytics including human discourse and\n knowledge; visualization techniques and tools.\n\n_Interaction design for culture and development_\nExample topics: cultural differences in interaction design; interaction design in developing countries; cross-\ncultural interactive systems for cultural heritage; sustainability and HCI;\n\n_Interactive Systems Technologies and Engineering_\nExample topics: 3D interaction and human architecture for interactive systems; interactive technologies;\nmodel-based approaches for engineering interactive systems; multimodality; robot development (building and\ndesigning robots); wearable interaction.\n\n_Methodologies for HCI_\nExample topics: user-centred design; participatory design; design and development processes methods,\ntechniques and tools for evaluating interactive systems,; methods for identifying end-user requirements for\ninteractive systems,; design rationale and traceability of design choices; requirements and needs analysis; task\n analysis and task modelling; usability; methods for studying user experience.\n\n_Social and Ubiquitous Interaction_\nExample topics: Computer-Supported Cooperative Work; HCI for mobile interactions; interaction on the move;\nsocial media; social aspects of HCI, mobility.\n\n_HCI for Justice and Equality_\nExample topics: HCI to support sustainable development; HCI to support reduction in food waste, water and\nenergy use; HCI to support freedom of expression; Consideration of gender, sexuality and ethnic diversity in\nHCI; HCI and the digital divide; HCI and inclusion of disabled and older people; HCI countering adversity.\n\n_Understanding users and human behaviour_\nExample topics: affective HCI and emotion; ethnographic studies; field reports and user studies; human\nperception; cognition and behaviour; interaction design and children.\n",
      #         "link": "https://new.precisionconference.com/submissions"
      # }
      

      # - label: Layout
      #   name: layout
      #   widget: hidden
      #   default: blog
      # - label: Title
      #   name: title
      #   widget: string
      # - label: Title
      #   name: title
      #   widget: string
      # - label: Publish Date
      #   name: date
      #   widget: datetime
      # - label: Description
      #   name: desc
      #   widget: markdown
      # - label: Body
      #   name: body
      #   widget: markdown

       